plugins {
    id 'com.android.application'
}

android {
    namespace 'com.linuxsuren.tvuvc'
    compileSdk 34

    ndkVersion '27.0.12077973'

    defaultConfig {
        applicationId "com.linuxsuren.tvuvc"
        minSdk 23
        targetSdk 24
        versionCode 7
        versionName "0.5.1"

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=none'
                abiFilters 'armeabi-v7a', 'arm64-v8a'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig false
    }

    lint {
        abortOnError false
    }
}
