plugins {
    id 'com.android.application'
}

android {
    namespace 'com.linuxsuren.tvuvc'
    compileSdk 34

    defaultConfig {
        applicationId "com.linuxsuren.tvuvc"
        minSdk 23
        targetSdk 23
        versionCode 1
        versionName "0.1.0"

        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=none'
                abiFilters 'armeabi-v7a'
            }
        }
    }

    externalNativeBuild {
        cmake {
            path 'src/main/jni/CMakeLists.txt'
            version '3.22.1'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        buildConfig false
    }

    lint {
        abortOnError false
    }
}
